### ISSUE TITLE
Simple scripts won't run. 

### ISSUE THREAD

**Issue by khrome83** [eliassjogreen/deno_webview#15]
In the examples, only loading from a remote resouce worked.

```
await new WebView({
  title: "Remote deno_webview example",
  url: `https://deno.land/`,
  width: 800,
  height: 600,
  resizable: true,
  debug: true,
  frameless: false,
}).run();
```

When I try to do this - 

```
await new WebView({
  title: "Local deno_webview example",
  url: `data:text/html,
    <html>
    <body>
      <h1>Hello from deno</h1>
    </body>
    </html>
    `,
  width: 800,
  height: 600,
  resizable: true,
  debug: true,
  frameless: false,
}).run();
```

The content within the webview is empty.

Here is a screenshot, notice body is empty - 

<img width="1035" alt="Screen Shot 2020-05-16 at 10 26 37 AM" src="https://user-images.githubusercontent.com/1844739/82123586-c3bf4180-975f-11ea-8126-84b438749bfa.png">

Deno does not throw any permissions isues. I tried a data URL with encoded string as well, no luck. 

Going to try a local file, but don't think that will work either. Any advice would be appreciated.

**Comment by khrome83** [comment]
I found an awful work around...

### main.ts
```
import { WebView } from "https://deno.land/x/webview/mod.ts";

const server = new Worker("./worker.ts", { type: "module", deno: true });

server.onmessage = async (e) => {
  console.log(e.data);

  await new WebView({
    title: "Local deno_webview example",
    url: "http://localhost:8000/",
    width: 800,
    height: 600,
    resizable: true,
    debug: true,
    frameless: false,
  }).run();
};
```

### worker.ts
```
import { serve } from "https://deno.land/std/http/server.ts";

const s = serve({ port: 8000 });
postMessage("http://localhost:8000/");

for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

Still working out issues. Have to kill it from CLI. Can't kill it from GUI. Have to see if I can get the correct signals and all...

**Comment by eliassjogreen** [comment]
What os are you running and deno version?

**Comment by khrome83** [comment]
Deno 1.0, and Mac OSX 10.15.4

**Comment by rauchg** [comment]
Same here I believe. Windows are empty on macOS with the provided example in README

![image](https://user-images.githubusercontent.com/13041/82154245-6a1f4b80-9821-11ea-8660-ef89630aac27.png)

**Comment by khrome83** [comment]
Funny to see you here @rauchg. I am about to move my local server in my workaround above to vercel.com using the now-deno.

**Comment by raichuk** [comment]
After some investigation on https://github.com/zserge/webview/ and specifically this issue https://github.com/zserge/webview/issues/177 I found a solution.

Updating the local `examples/multiple.ts` to this:

```
import { WebView } from "../mod.ts";

const html = `
    <html>
    <body>
      <h1>Hello from deno</h1>
    </body>
    </html>
`;

const webview1 = new WebView({
  title: "Multiple deno_webview example",
  url: `data:text/html,${encodeURIComponent(html)}`,
  width: 400,
  height: 200,
  resizable: true,
  debug: true,
  frameless: false,
});

await webview1.run();
```

As you can see on the issue, the content needs to be encoded in order to gets recognized by the webview.
I've tried this with deno 1.0.0 and macOS 10.15.4.

In addition and not related to encoding but to using local files, this worked fine too, but if it includes local files (js, css, svg, etc) you will have to change the paths of them to the true path on fs, if not the webview will fail with: `allow to load local resource` trying to get them from root of fs.

![image](https://user-images.githubusercontent.com/658706/82244460-ac2ab900-9917-11ea-8f57-4b3005e5a815.png)

**Comment by khrome83** [comment]
@raichuk - nice! So strange, I tried encoding as well. I wonder why you had success?

I had pasted in a already encoded string, so maybe it has to be the fact you used the method?

I will try this. Nice find.

**Comment by raichuk** [comment]
@khrome83 When I first tried with the sample string on the C++ issue and later the encoding.. strange!

Glad it worked and helped!

**Comment by khrome83** [comment]
@raichuk - it worked for me as well.

I did try this, here is the snippet `data:text/html,%3Ch1%3EHello%2C%20World!%3C%2Fh1%3E`

I got it from here - https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

@eliassjogreen - I don't know if I would consider this a bug. I feel like it might be just how forgiving the browser is. I don't know if you want to "protect" the user. But updating the examples to match this would make sense IMHO, and then close the bug.

**Comment by eliassjogreen** [comment]
Thanks for digging a little deeper for me. I will update the readme and might add a check in the constructor for macos
