### ISSUE TITLE
Window blank on mac

### ISSUE THREAD

**Issue by mathiasrw** [eliassjogreen/deno_webview#18]
The window is blank on mac when running the example code

    deno run -A -r --unstable https://deno.land/x/webview/examples/multiple.ts

![image](https://user-images.githubusercontent.com/1063454/82131345-9f517c80-97d4-11ea-8d39-79409701f335.png)

Deno v1.0.0

**Comment by eliassjogreen** [comment]
Possibly dupe of #15

**Comment by khrome83** [comment]
Yeah, same issue.
