### ISSUE TITLE
Unable to load local webserver webpages

### ISSUE THREAD

**Issue by gjuoun** [eliassjogreen/deno_webview#21]
I'm trying to load webpages from local, but it doesn't load.
Is there any alternative way to achieve it?

```ts
import { WebView } from "https://deno.land/x/webview/mod.ts";


await new WebView({
  title: "Remote deno_webview example",
  url: `http://127.0.0.1:8080/index.html`,
  width: 800,
  height: 600,
  resizable: true,
  debug: true,
  frameless: false,
}).run();
```

**Comment by hashrock** [comment]
Would you have allowed the CORS on local server? I'm doing something similar in my repository, so you can refer to it

https://github.com/hashrock-sandbox/study-deno-text-editor/blob/master/server.ts#L11

**Comment by gjuoun** [comment]
I tried exactly the same code you provided. 
But still get the same result which is a blank page. (any other domain than localhost would work)

Maybe because of Windows? I'm not sure.
![image](https://user-images.githubusercontent.com/8935612/82401139-619c6000-9a2f-11ea-8560-2225475be71a.png)

**Comment by hashrock** [comment]
@gjuoun 
Are you using Windows?
You might want to use Edge Devtools to get detailed error messages.
https://pspdfkit.com/blog/2018/edge-devtools-uwp/

**Comment by gjuoun** [comment]
It's indeed Edge sandbox restrictions. 

Run this in with admin privilege solved the problem.
```
> CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"
```

Thank you!
