### ISSUE TITLE
how load local path page?

### ISSUE THREAD

**Issue by blogwy** [eliassjogreen/deno_webview#26]
eg:
const webview3 = new WebView({
  title: "Multiple deno_webview example",
  url: './src/view/index.html',
  width: 400,
  height: 200,
  resizable: true,
  debug: true,
  frameless: false,
});

**Comment by eliassjogreen** [comment]
What OS, deno version and how does your directory look? You don't seem to be even running the `.run` or `.step` method for the webview.
