### ISSUE TITLE
Compiling webview-sys with edge on ci

### ISSUE THREAD

**Issue by eliassjogreen** [eliassjogreen/deno_webview#3]
Currently it throws a fat linker error but it should be solvable.

**Comment by eliassjogreen** [comment]
Log: https://github.com/eliassjogreen/deno_webview/runs/499222235?check_suite_focus=true

**Comment by markkovari** [comment]
The raw output of the [build error](https://pipelines.actions.githubusercontent.com/hOAiSK30k7lZYFAHoasJV3cYRMjVa34ebhSOpipe5ler2U3mCg/_apis/pipelines/1/runs/22/signedlogcontent/5?urlExpires=2020-03-11T18%3A08%3A20.4682597Z&urlSigningMethod=HMACV1&urlSignature=WPaBTVdzxVoBtenELwRka16YnkJsWgZ9fOiw4kxFGJI%3D) from the log entry`2020-03-10T23:42:24.7314141Z`
As far I understood from related issues the problems are with the windows-rust bindings.
Similar issues can be found here: 
https://github.com/davisking/dlib/issues/1448
https://social.msdn.microsoft.com/Forums/windows/en-US/d0026ac6-0f14-495e-b5c6-19648a97cba4/mismatch-detected-for-runtimelibrary-value-mddynamicrelease-doesnt-match-value?forum=vclanguage
It seems it will be somewhere in the cmake section and specially in the windows part of it.

**Comment by eliassjogreen** [comment]
Somehow [webview_edge.cpp](https://github.com/Boscop/web-view/blob/master/webview-sys/webview_edge.cpp) differs from [webview_mshtml.c](https://github.com/Boscop/web-view/blob/master/webview-sys/webview_mshtml.c) in the way it's linked creating the linker mismatch error.

**Comment by eliassjogreen** [comment]
Probably caused by the cpp version being different:
[```.flag_if_supported("/std:c++17");```](https://github.com/Boscop/web-view/blob/9597833d872cf2e85aeac3901f6b59662b559d3d/webview-sys/build.rs#L28)

[Linker Tools Error LNK2038](https://docs.microsoft.com/en-us/previous-versions/jj889284(v=vs.140)?redirectedfrom=MSDN):
> Indicates the version of the C++ Standard Library and C runtime that's used by an app or library. Code that uses one version of the C++ Standard Library or C runtime is incompatible with code that uses a different version. For more information, see /MD, /MT, /LD (Use Run-Time Library).

**Comment by IllusionPerdu** [comment]
Hello in my local computer i can compile with edge when i create a file ".cargo\config" with

```
[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
```

**Comment by eliassjogreen** [comment]
I tried that yesterday but using it as an environmental variable. It compiled but did not  use edge over ie. Can you confirm that it uses edge?

**Comment by IllusionPerdu** [comment]
and i have change the webview2  inmultiple.ts with (for test) 
```
const webview2 = new WebView({
  title: "Multiple deno_webview example",
  url: `data:text/html,
    <html>
    <body>
      <h1 id="h1">2 Nav</h1>
      <script>var elem = document.getElementById("h1"); elem.innerHTML = window.navigator.userAgent;</script>
    </body>
    </html>
    `,
  width: 800,
  height: 600,
  resizable: true,
  debug: true,
  frameless: false
});
```

I set the dev with `set DEV=file://./target/release`

and exec the exmple with  `deno -A --reload examples\multiple.ts`

the window 2 content is 
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19041`

Yes it's work ;)

Sorry for my bad english !!!
