### ISSUE TITLE
Building locally - File not found

### ISSUE THREAD

**Issue by parliament718** [eliassjogreen/deno_webview#34]
I'm having trouble running examples using locally built deno_webview

I built using ```deno run -A scripts/build.ts```  

```echo $DENO_WEBVIEW_PLUGIN_BASE```

> file:///Users/user/Documents/code/deno_webview/target/release

```deno run -A scripts/dev.ts examples/multiple.ts```
<img width="743" alt="Screen Shot 2020-06-06 at 8 35 39 PM" src="https://user-images.githubusercontent.com/3580270/83957322-5b7eef80-a835-11ea-96f1-bb7f3f48b3ee.png">

Is deno_webview supposed to be generated in target/release? 

<img width="691" alt="Screen Shot 2020-06-06 at 8 38 36 PM" src="https://user-images.githubusercontent.com/3580270/83957349-bdd7f000-a835-11ea-9563-3a02871794c2.png">

**Comment by eliassjogreen** [comment]
Do you have rust and cargo installed in path?

**Comment by eliassjogreen** [comment]
What OS are you on and do you have deno and cargo installed in path?
