### ISSUE TITLE
Use cache in production

### ISSUE THREAD

**Issue by swwind** [eliassjogreen/deno_webview#4]
I think the cache should be used in the production environment, but I found that the code uses the cache only in the development environment. I don't know if this is a small mistake or... any special reason to do that?

https://github.com/eliassjogreen/deno_webview/blob/4dfd47c05fc952c0d4e45f77f368b58eb4643a4a/plugin.ts#L11

**Comment by eliassjogreen** [comment]
Yeah that's a mistake and will be fixed asap (later this afternoon unless you would like to do a pr for it)

**Comment by buckle2000** [comment]
It's not using the cached plugin when I try to run the example script. I am not developing deno_webview, so why not use cache? https://github.com/eliassjogreen/deno_webview/releases/download/0.4.0/libdeno_webview.so has version in it, so it wouldn't matter.

Not caching only makes sense when I'm developing deno_webview itself.

**Comment by eliassjogreen** [comment]
Sorry, should be fixed now. Why the plugin is downloaded to `./.deno_plugins/` i don't know as it is from the [deno-plugin-prepare](https://github.com/manyuanrong/deno-plugin-prepare) module.
